# coding: utf-8

"""
    Mail API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from clients.http.mail_service.models.content import Content
from clients.http.mail_service.models.model_from import ModelFrom
from clients.http.mail_service.models.raw import Raw
from clients.http.mail_service.models.to_item import ToItem
from typing import Optional, Set
from typing_extensions import Self

class Item(BaseModel):
    """
    Item
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, alias="ID")
    var_from: Optional[ModelFrom] = Field(default=None, alias="From")
    to: Optional[List[ToItem]] = Field(default=None, alias="To")
    content: Optional[Content] = Field(default=None, alias="Content")
    created: Optional[StrictStr] = Field(default=None, alias="Created")
    mime: Optional[Any] = Field(default=None, alias="MIME")
    raw: Optional[Raw] = Field(default=None, alias="Raw")
    __properties: ClassVar[List[str]] = ["ID", "From", "To", "Content", "Created", "MIME", "Raw"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Item from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of var_from
        if self.var_from:
            _dict['From'] = self.var_from.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in to (list)
        _items = []
        if self.to:
            for _item_to in self.to:
                if _item_to:
                    _items.append(_item_to.to_dict())
            _dict['To'] = _items
        # override the default output from pydantic by calling `to_dict()` of content
        if self.content:
            _dict['Content'] = self.content.to_dict()
        # override the default output from pydantic by calling `to_dict()` of raw
        if self.raw:
            _dict['Raw'] = self.raw.to_dict()
        # set to None if mime (nullable) is None
        # and model_fields_set contains the field
        if self.mime is None and "mime" in self.model_fields_set:
            _dict['MIME'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Item from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ID": obj.get("ID"),
            "From": ModelFrom.from_dict(obj["From"]) if obj.get("From") is not None else None,
            "To": [ToItem.from_dict(_item) for _item in obj["To"]] if obj.get("To") is not None else None,
            "Content": Content.from_dict(obj["Content"]) if obj.get("Content") is not None else None,
            "Created": obj.get("Created"),
            "MIME": obj.get("MIME"),
            "Raw": Raw.from_dict(obj["Raw"]) if obj.get("Raw") is not None else None
        })
        return _obj
