# coding: utf-8

# flake8: noqa
"""
    Register API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from clients.http.register_service.models.http_validation_error import HTTPValidationError
from clients.http.register_service.models.rating import Rating
from clients.http.register_service.models.registration import Registration
from clients.http.register_service.models.user import User
from clients.http.register_service.models.user_envelope import UserEnvelope
from clients.http.register_service.models.user_role import UserRole
from clients.http.register_service.models.validation_error import ValidationError
from clients.http.register_service.models.validation_error_loc_inner import ValidationErrorLocInner
